
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: recrutech-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recrutech_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - recrutech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # The auth-service has been commented out to allow manual startup in debug mode
  # To run the auth service manually, use your IDE's debug configuration or run:
  # cd recrutech-services/recrutech-auth
  # mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
  #
  # auth-service:
  #   build:
  #     context: ..
  #     dockerfile: recrutech-auth/Dockerfile
  #   container_name: recrutech-auth-service
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     # Database Configuration
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_NAME=recrutech_auth
  #     - DB_USERNAME=${DB_USERNAME:-user}
  #     - DB_PASSWORD=${DB_PASSWORD:-password}
  #     - DB_SSL=true
  #     - DB_PUBLIC_KEY=false
  #     
  #     # Connection Pool Configuration
  #     - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
  #     - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
  #     
  #     # JWT Configuration
  #     - JWT_PUBLIC_KEY=/run/secrets/jwt_public_key
  #     - JWT_PRIVATE_KEY=/run/secrets/jwt_private_key
  #     - JWT_AUDIENCE=recrutech-api
  #     - JWT_EXPIRATION=43200000
  #     - JWT_REFRESH_EXPIRATION=604800000
  #     
  #     # CORS Configuration
  #     - CORS_ALLOWED_ORIGINS=http://localhost:3000
  #     
  #     # Server Configuration
  #     - SERVER_PORT=8082
  #     - SSL_ENABLED=${SSL_ENABLED:-false}
  #     
  #     # Logging Configuration
  #     - SECURITY_LOG_LEVEL=INFO
  #     - APP_LOG_LEVEL=INFO
  #     
  #     # Rate Limiting Configuration
  #     - RATE_LIMITING_ENABLED=true
  #     - RATE_LIMITING_LIMIT=10
  #     - RATE_LIMITING_REFRESH_PERIOD=60
  #     - RATE_LIMITING_TIMEOUT=30
  #   volumes:
  #     - ./keys:/run/secrets
  #   networks:
  #     - recrutech-network
  #   restart: always
  #   secrets:
  #     - jwt_public_key
  #     - jwt_private_key

networks:
  recrutech-network:
    driver: bridge

volumes:
  mysql-data:

secrets:
  jwt_public_key:
    file: ./keys/public_key.pem
  jwt_private_key:
    file: ./keys/private_key.pem